---
- name:  ACI Get Interface Ports
  hosts: apic
  connection: local
  gather_facts:  false

  vars_files:
    - external_vars.yml

  tasks:
    - name: Use REST to gather interface ports with a PolicyGroup assigned
      aci_rest:
        host: "{{ apic }}"
        username: "{{ aci_username }}"
        password: "{{ aci_password }}"
        validate_certs: "{{ aci_validate_certs }}"
        method: get
        path: '/api/node/mo/uni/infra/accportprof-{{ aci_leaf }}_IntProf.json?query-target=subtree&target-subtree-class=infraHPortS&query-target-filter=not(wcard(infraHPortS.dn,"__ui_"))&target-subtree-class=infraPortBlk,infraSubPortBlk,infraRsAccBaseGrp&query-target=subtree&subscription=no'
      delegate_to: localhost
      register: query_result

# damcfarl
# ansible-playbook port_rest_aci_json.yml -i hosts -vvv | grep '/rsaccBaseGrp|tDn'