---
- name: Use REST to add description to interface
  hosts: apic1
  connection: local
  gather_facts:  false

  vars_files:
    - 1-external_vars.yml

  tasks:
    - name: "Add description to interface"
      aci_rest:
        host: "{{ host }}"
        username: "{{ user }}"
        password: "{{ password }}"
        validate_certs: "{{ validate_certs }}"
        method: post
        path: '/api/node/mo/uni/infra/hpaths-{{ leaf }}_eth1_{{ eth_if }}.json'
        content: { 
     
    "infraHPathS": {
        "attributes": {
            "rn": 'hpaths-{{ leaf }}_eth1_{{ eth_if }}',
            "dn": 'uni/infra/hpaths-{{ leaf }}_eth1_{{ eth_if }}',
            "descr": "{{ interface_description }}",
#           "descr": "dm change to N3K-2 Eth 1/45",
            "name": "{{ leaf }}_eth1_{{ eth_if }}"
        },
        "children": [
            {
                "infraRsHPathAtt": {
                    "attributes": {
                        "dn": 'uni/infra/hpaths-{{ leaf }}_eth1_{{ eth_if }}/rsHPathAtt-[topology/pod-1/paths-{{ leaf }}/pathep-[eth1/{{ eth_if }}]]',
                        "tDn": 'topology/pod-1/paths-{{ leaf }}/pathep-[eth1/{{ eth_if }}]'
                    }
                }
            }
        ]
    }
}

      delegate_to: localhost
      register: query_result

# damcfarl
# ansible-playbook -i hosts 1-interface_description.yml
#
