--- 
- 
  connection: local
  gather_facts: false
  hosts: apic1
  name: "Use REST to add description to interface"
  tasks: 
    - 
      aci_rest: 
        content: 
          infraHPathS: 
            attributes: 
              descr: "{{ interface_description }}"
              dn: "uni/infra/hpaths-{{ leaf }}_eth1_{{ eth_if }}"
              name: "{{ leaf }}_eth1_{{ eth_if }}"
              rn: "hpaths-{{ leaf }}_eth1_{{ eth_if }}"
            children: 
              - 
                infraRsHPathAtt: 
                  attributes: 
                    dn: "uni/infra/hpaths-{{ leaf }}_eth1_{{ eth_if }}/rsHPathAtt-[topology/pod-1/paths-{{ leaf }}/pathep-[eth1/{{ eth_if }}]]"
                    tDn: "topology/pod-1/paths-{{ leaf }}/pathep-[eth1/{{ eth_if }}]"
        host: "{{ host }}"
        method: post
        password: "{{ password }}"
        path: "/api/node/mo/uni/infra/hpaths-{{ leaf }}_eth1_{{ eth_if }}.json"
        username: "{{ user }}"
        validate_certs: "{{ validate_certs }}"
      delegate_to: localhost
      name: "Add description to interface"
      register: query_result
  vars_files: 
    - 1-external_vars.yml


